MindscapeHQ/raygun4node

lib/raygun.messageBuilder.js, test/raygun.messageBuilder_test.js
Fix deprecation warnings in the log when using the express handler.
```js
express deprecated req.host: Use req.hostname instead node_modules/raygun/lib/raygun.messageBuilder.js:114:26
```
=> Fix usage of deprecated method for request host

lib/raygun.messageBuilder.js, package.json, test/raygun.messageBuilder_test.js
Need to keep checking request.host so raygun4node still works under Express3
Also updates the package version to 0.6.1
=> Add express3 support back

lib/raygun.messageBuilder.js
It wasn't doing that if you passed it an object, it would only do it if
you gave it a function that returned an object. We're calling the
user function earlier in the stack so we can give it the request object
so it's already been evaluated at this point.
=> setUser should check if user data is already an object

lib/raygun.transport.js
Request errors should be caught and logged out, otherwise the node process will crash if it can't connect to Raygun.
=> Handle request errors and log out to console

lib/raygun.messageBuilder.js, test/raygun.messageBuilder_test.js
it happened in our team a few times that developers would pass a string instead of an error instance to Raygun and then the log was full of `NoMessage` errors. This is an easy fix for this. I'm sure others have run into this as well.
=> allow passing in a string as an error

README.md, lib/raygun.messageBuilder.js, package.json
Fixes a weird as edge case where if you pass an object through on the exception parameter, it kinda gets converted to a string. This is fine in Raygun, but it breaks once it reaches the notification stuff.
Not an overly common problem, I'm sure, but has come up through support and it seems like a worthwhile fix.
=> Object to string

lib/raygun.transport.js
`new Buffer` has been deprecated and now emits a message. The particular
form of it we were using was not a vulnerability as far as I am aware,
due to passing a string value rather than a manual size, but it's still
recommended to update to `Buffer.from`.
https://nodejs.org/gl/docs/guides/buffer-constructor-deprecation/
=> Replace deprecated Buffer constructor with Buffer.from

examples/express-sample/app.js, examples/express-sample/package-lock.json, examples/express-sample/package.json
Primarily just updating vulnerable dependencies, but I also swapped out `node-compass` for `node-sass-middleware` to save a Ruby dependency.
This PR also adds a `package-lock.json`, which pins exact dependency versions to help ensure it's easier to run this example in the future.
=> Update express example

.gitignore, .travis.yml, lib/raygun.messageBuilder.ts, lib/raygun.offline.ts, lib/raygun.transport.ts, lib/raygun.ts, lib/types.ts, package-lock.json, package.json, test/raygun.messageBuilder_test.js, test/raygun_send_test.js, test/raygun_test.js, tsconfig.json, tslint.json
This PR overhauls the project to TypeScript strict mode.
The main rationale for this was easing the process of adding new features to this repo without compromising existing behaviour, and having a reliable set of TypeScript definitions for our users that are guaranteed to stay up to date.
As much as possible this pull request retains all the original behaviour of the module prior to refactor, even if that meant compromising on type safety for the time being.
This means that some of the annotations feel a little tortured, as there are a few places where we initialize a class and then call `init`, rather than fully constructing the object up front. This means that the type system has to reflect the possibility that the user never called `.init`, which is a real concern, but adds a lot of …
=> Typescript

lib/raygun.ts, package-lock.json, package.json, test/raygun_express_test.js, test/utils.js
This PR has been opened against the `typescript` branch, to simplify the diff. Once the `typescript` branch is merged this PR should be updated to merge into master.
-----
Previously, this provider made no differentiation between handled
errors (where a user directly reports a caught error with .send) and an
unhandled error, where an indirect mechanism like the express error
handler is used to catch and report an error.
Since the express middleware is currently the only source of unhandled
errors, we can start by adding the "UnhandledException" tag to all
errors caught by the express middleware.
The bulk of this change adds a test to exercise the express middleware.
Other tests make use of `nock` to stop the tests from hitting the API,
but this is a tad inelegant for our case as we want …
=> Tag unhandled exceptions from express middleware

lib/raygun.batch.ts, lib/raygun.offline.ts, lib/raygun.transport.ts, lib/raygun.ts, lib/timer.ts, lib/types.ts, package-lock.json, package.json, test/raygun_batch_test.js, test/raygun_express_test.js, test/raygun_offline_test.js, test/utils.js
You can now pass {batch: true} when calling `.init` to enable the batch
transport.
When this option is enabled, errors will be placed in a queue and
processed at a regular interval.
This should cut down on transmission overhead if there are a large
number of errors in short succession.
You can further control the frequency at which batches are processed by
providing a `batchFrequency` option when initializing, which specifies
the interval between batches in milliseconds.
TODO:
=> Support batched error reporting

lib/raygun.ts, lib/types.ts, package-lock.json, package.json
This branch adds integration with `raygun-apm` that allows for linked exceptions in the Raygun app.
We now generate a UUIDv4 to serve as a correlation id, as pass that both to the crash reporting endpoint and to the apm module. This allows the generated trace to reference the linked exception correctly.
=> Notify apm of exceptions

package.json
Since the express types are imported and used in [`raygun.ts`](https://github.com/MindscapeHQ/raygun4node/blob/master/lib/raygun.ts), they should be shipped with raygun. Otherwise the user needs to add the types manually or this error will appear:
```
node_modules/raygun/build/raygun.d.ts(2,54): error TS2307: Cannot find module 'express' or its corresponding type declarations.
```
=> fix: Move express types to dependencies

lib/raygun.ts, test/raygun_express_test.js
This is a fix for a regression I introduced during the TypeScript
overhaul.
Previously we would always call this.user, even if the request was null
or undefined. The regressed behavior would only call this.user if the
request was present, either from the middleware or if it was passed
manually.
This commit reverts the behavior back to what it was previously, and
adds a unit test to guard against future unintended changes to this
behaviour.
=> Fix raygunClient.user not being called if request is missing

lib/raygun.ts
Allows our customers to make use of our type definitions.
With this change in place, this example works as expected:
```
import * as Raygun from "raygun4node";
class Example {
_raygun: Raygun.Client;
constructor() {
this._raygun = new Raygun.Client().init({apiKey: 'foo'});
}
}
```
Unfortunately, this still doesn't work for the `import Raygun from "raygun4node"' case, as TypeScript will still report that it can't find a namespace called "Raygun".
It seems like TypeScript doesn't have great support for typing default exports, at least the way we have this set up. I think this could be improved but would likely be a breaking change, so this is probably a good place to start.
=> Export Raygun.Client type

CHANGELOG.md, lib/raygun.messageBuilder.ts, package-lock.json, package.json, test/raygun.messageBuilder_test.js, test/raygun_express_test.js
Previously, when calling raygunClient.send("test"), the exception would be formatted as if we had sent raygunClient.send(["t", "e", "s", "t"]).
This was as a result of passing the error value to humanString, which is intending for serializing objects and arrays in a pleasant way.
This change avoids applying any formatting to exceptions passed as a string.
I've also included a release commit so that we can promptly publish after merging.
Fixes #114
=> Fix exception formatting when passing string to send

lib/raygun.batch.ts, lib/raygun.ts, test/fixtures/batch_lifecycle.js, test/raygun_batch_lifecycle_test.js
Previously, using batch: true would keep the process alive indefinitely due to the use of setInterval.
This is often okay for webapps which run until killed or crashed, but causes problems when using crash reporting in a short-lived script.
This commit replaces the interval based process loop with one based on setInterval.
The timer is now inactive until messages are queued for sending, at which point we activate the timer loop.
Process will send batches, and restart the loop if there are any remaining messages. If not, the loop will stop until new messages come in.
Fixes #122
=> Fix batch transport keeping process alive

lib/raygun.batch.ts, test/raygun_express_test.js
Previously, if we attempted to send a massive error (>1600kb) via batch
mode, it would stall all batch processing.
This can cause all sorts of problems. Now, we dicard any messages this
large and log a warning.
This is better than the alternative behaviour of attempting to send
anyway, as the Raygun API will disconnect us if we intend to send that
much data, which causes an annoying EPIPE error.
=> Fix massive errors causing batch processing stalls

.gitignore, lib/raygun.ts, package-lock.json, package.json, test/raygun.messageBuilder_test.js, test/raygun_batch_lifecycle_test.js, test/raygun_express_test.js
This PR upgrades dependencies in the root project
- Used `node-version-check` to review and perform upgrades.
- Recreated the `package-lock.json` to fix dependency issues.
- fix mix up between `express` `Request` type and Raygun's `RequestParams` type.
- import `deepEqual` from the `assert` package.
- fixes in the `tap` test command
- replaces the removed `assert` calls from the `tap` project with the `tap` equivalent.
TODO in a different PR: 
- Update dependencies for the example projects.
- Replace `tslint` with `eslint`.
- Setup `eslint` in GitHub Actions and fix all static analysis warnings.
**After fixing dependencies and tests:**
```bash
$ npm ci
npm WARN deprecated tslint-react@5.0.0: tslint-react is deprecated along with TSLint
npm WARN deprecated tslint@6.1.3: TSLint has been …
```
=> fix: Updating dependencies and fixes

.github/bug_report.md, .github/feature_request.md, pull_request_template.md
Adding some process templates as a starting point. We can tweak further down the track, but this will help streamline flows as well as internal/external requests.
=> chore: adding PR, bug report and feature request templates

examples/express-sample/app.js, examples/express-sample/package-lock.json, examples/express-sample/package.json, examples/express-sample/readme.md, examples/using-domains/app.js, examples/using-domains/package-lock.json, examples/using-domains/package.json, examples/using-domains/readme.md
Take the two examples in the repo and upgrade dependencies. Also ensure that they use the `raygun4node` found in the repo, not the one from `npm`.
**Updates**
- Upgrade dependencies in `examples/express-sample`.
- Upgrade dependencies in `examples/using-domains`.
- Ensure both examples use the `raygun` node package from the repo, not the one hosted in `npm`.
- Adds multiple `console.log` to `examples/using-domains`.
- Fixes indentation in `examples/using-domains/app.js`.
Note: The `eslint` config is done in #156 and includes the files in the `examples` folders.
- Run both examples.
=> chore: #148 upgrade examples

.github/pr.yml
- **Purpose**: Enforce the user of Conventional Commits in PR titles
- **Approach**: Adds a GitHub Actions configuration that runs on PR creation and update
**Updates**
- Added `pr.yml` configuration file.
- The file contains the GitHub Actions configuration, with the following steps:
1. Checks if the PR title is valid
2. If not, it adds an info message
3. If then is fixed, the info message is removed
- Needs to be merged into `develop` to see it in action.
- Uses a standard template found in other repos so it should work the same.
=> ci: add PR title checks

eslint.config.mjs, test/raygun_express_test.js
- **Purpose**: Remove the `no-useless-catch` eslint rule ignore setting
- **Approach**: Remove rule and fix code
- **Depends on**: #177
- This change also concludes the `eslint` setup.
- Closes #158 
**Updates**
- Removed rule from `eslint.config.mjs`
- Removed the useless `catch` statements.
- A `catch` and `throw` is not necessary, since we can just throw the original error, and the `finally` block will be called anyway.
- Rerun the tests and eslint process.
- Only test files were affected.
=> refactor: #158 remove no-useless-catch eslint rule

CHANGELOG.md, LICENSE-MIT, README.md, eslint.config.mjs, package.json, test/raygun_express_test.js
- **Purpose**: Prepare package for release
- **Approach**: Bump version number and update changelog.
**Updates**
- Sets version to `0.14.0`
- Adds Changelog.
=> chore: Prepare for Release 0.14.0

lib/raygun.messageBuilder.ts, test/raygun.messageBuilder_test.js
- **Purpose**: `filterKeys` method uses recursion to explore the provided object, this can potentially cause infinite recursion and eventually throw the "Maximum call stack size exceeded" error.
- **Approach**: Adds an `explored` parameter to the recursive `filterKeys` method, to check if the incoming object has already been explored or not.
**Updates**
- TDD approach: Created a test that can reproduce the issue, using a cyclic object, and causes a "Maximum call stack size exceeded" error, then implemented the solution to fix it.
- Implementation:
- Added `explored: Set<object>` as parameter (it is `null` by default).
- When iterating over the object children, if the child is in the explored `Set`, remove from parent. Same as when applying filters.
- When calling to …
=> fix: #186 avoid infinite recursion in filter method

examples/express-sample/bin/www, examples/express-sample/config/default.json, examples/express-sample/config/production.json, examples/express-sample/public/stylesheets/style.css, examples/express-sample/public/stylesheets/style.scss, examples/using-domains/config/default.json, examples/using-domains/config/production.json, package.json
- **Purpose**: Ensure that non-dot-js files are also formatted correctly
- **Approach**: Apply prettier to all files in the `examples` directory
- Closes #204 
**Updates**
- Update command in `package.json`.
- Apply prettier command.
- GitHub CI should pass.
=> chore: apply prettier to all files in examples

lib/raygun.ts, test/raygun_unhandled_rejection_app.js, test/raygun_unhandled_rejection_test.js
- **Purpose**: When a user forgets to `.catch()` a Promise, and this fails, Raygun4Node will capture the error and send it automatically
- **Approach**: Similar to the uncaught exception handler, but for Promises, using `unhandledRejection`.
**Updates**
- Added `process.on` handler.
- Added tags to the `sendSync` method, to help differentiate between "uncaught exceptions" and "unhandled rejections".
- Implemented test.
- Verified using unit tests.
- Verified running simple app:
```js
// Setup Raygun
var raygun = require("raygun");
var raygunClient = new raygun.Client().init({ apiKey: config.Raygun.Key, reportUncaughtExceptions: true });
new Promise(() => {
throw new Error("test");
}).then(() => {
// Should not be reached
});
```
=> fix: #137 Report unhandled rejection promises automatically

CHANGELOG.md, package-lock.json, package.json
- **Purpose**: Prepare release 1.1.0
- **Approach**: Update package version and changelog
**Updates**
- Generate CHANGELOG entry, order by feat -> fix -> chore.
- Bump version in `package.json` to `1.1.0`.
- Run `npm install` to update `package-lock.json`.
Run `npm publish --dry-run`:
```
➜  raygun4node git:(prepare-1.1.0) npm publish --dry-run
> raygun@1.1.0 prepare
> tsc
npm notice
npm notice 📦  raygun@1.1.0
npm notice Tarball Contents
npm notice 5.3kB CHANGELOG.md
npm notice 20.8kB README.md
npm notice 0B build/.gitkeep
npm notice 1.2kB build/raygun.batch.d.ts
npm notice 6.1kB build/raygun.batch.js
npm notice 470B build/raygun.breadcrumbs.d.ts
npm notice 204B build/raygun.breadcrumbs.express.d.ts
npm notice 942B build/raygun.breadcrumbs.express.js
npm notice 4.2kB …
```
=> chore: Prepare release 1.1.0

lib/raygun.sync.transport.ts
- **Purpose**: Adds clarification to why the sync transport catches all errors internally
- **Approach**: Add comments and console error log
- Closes: #196 
- To merge after 1.1.0 is released.
**Updates**
- Removes old TODO comment.
- Add explanation comment
- Change `console.log` to `console.error`.
- None
=> docs: #196 add documentation on handling errors in sync transport

README.md, lib/raygun.messageBuilder.ts, lib/raygun.ts, lib/types.ts, test/raygun.messageBuilder_test.js, test/raygun_async_send_test.js
- **Purpose**: Adds functionality for custom timestamp when reporting errors, requested in #65
- **Approach**: Adds the `timestamp` parameter to the `send()` method as optional config param.
- Closes #65 
**Updates**
- Add `timestamp` to `SendParameters`.
- `timestamp` uses the standard `Date` type or can be passed as `number`.
- Implemented tests
- Updated README docs
- Tested in example.
- Implement tests
=> feat: #65 Custom timestamp parameter

lib/raygun.batch.ts, lib/raygun.ts, lib/types.ts, test/raygun_express_test.js
- **Purpose**: Cleanup batch processing callbacks 
- **Approach**: Removing the old callback type, replacing it by an alternative based on Promises
- Closes #199 
**Updates**
- Created `PromiseReference` to handle the promise's `reject` and `resolve` methods.
- Replaced `Callback` with `PromiseReference`.
- Improved the tests
Note: The original `Callback` type should be eventually removed
- Implement unit tests.
- Run express example with `batch: true` to test batch processing
=> refactor: #199 batch callbacks

README.md, lib/raygun.breadcrumbs.ts
- **Purpose**: Resolve question raised in #224 
- **Approach**: Checked how source map processing works on Raygun and checked if Breadcrumbs can be also processed.
**Updates**
Checked with the team, Raygun docs and setup proper source mapping in a sample project.
Then I verified that Raygun doesn't process Breadcrumb attached source lines like with stacktraces. As well, the API is missing the actual filename and the column number, which are necessary by the source maps.
- Removed TODO
- Added clarification in README
- None, just code cleanup.
=> chore: #224 add clarification on sourcemaps and breadcrumbs

README.md, examples/express-sample/package-lock.json, examples/express-sample/routes/index.js, lib/raygun.messageBuilder.ts, lib/raygun.ts, lib/types.ts, test/raygun_express_test.js
- **Purpose**: Improve how users can provide user information to their error reports
Users have previously complained that the current implementation, based on the request, cannot be used in all situations. (see comments in #218).
The other older way, was to call to a global `setUser(user)` method, but that will cause problems when handling multiple requests by the same client, as not all requests are linked to the same user.
To fix that, I take inspiration on how the `raygun4net` package does it: https://github.com/MindscapeHQ/raygun4net/blob/ff5ef7eb6a3adaa7fdd49f2cd835fe8e68aef63d/Mindscape.Raygun4Net4/RaygunClient.cs#L339
By allowing users to pass the user information in the `send()` method, they can customize the way they provide the user information and ensure that …
=> feat: #218 Optional `userInfo` in `send()`

CHANGELOG.md, package-lock.json, package.json
- **Purpose**: Changelog and version bump on `package.json`
- **Approach**: Update changelog and increase minor version.
- Depends on https://github.com/MindscapeHQ/raygun4node/pull/269
- Depends on https://github.com/MindscapeHQ/raygun4node/pull/263
**Updates**
- Updated CHANGELOG
- Update `package.json`
- Update `package-lock.json` through the `npm install`
Run `npm publish --dry-run`
```
npm publish --dry-run
> raygun@1.2.0 prepare
> tsc
npm notice
npm notice 📦  raygun@1.2.0
npm notice Tarball Contents
npm notice 6.4kB CHANGELOG.md
npm notice 21.4kB README.md
npm notice 0B build/.gitkeep
npm notice 1.3kB build/raygun.batch.d.ts
npm notice 5.5kB build/raygun.batch.js
npm notice 470B build/raygun.breadcrumbs.d.ts
npm notice 204B build/raygun.breadcrumbs.express.d.ts …
```
=> chore: Prepare changelogs and version bump 1.2.0

README.md, lib/raygun.messageBuilder.ts, lib/types.ts, test/raygun.messageBuilder_test.js
- **Purpose**: Enables `isAnonymous` param in User Info payload
As discussed internally, developers using this package should be able to set the `isAnonymous` parameter independently if another parameter is set.
For that, I added the `isAnonymours` property to `RawUserData` and the required logic for it.
**Updates**
- Added property
- Modified message builder logic
- Updated tests
- Updated tests
- Tested on express-example
=> fix: #273 enable isAnonymous parameter

CHANGELOG.md, package-lock.json, package.json
- **Purpose**: Prepare release 2.0.0
- **Approach**: Update changelog and package files
**Updates**
- Update `CHANGELOG.md`
- Update `package.json`
- Perform `npm install` to update `package-lock.json`
dry run
```
npm publish --dry-run
> raygun@2.0.0 prepare
> tsc
npm notice
npm notice 📦  raygun@2.0.0
npm notice Tarball Contents
npm notice 7.2kB CHANGELOG.md
npm notice 21.2kB README.md
npm notice 0B build/.gitkeep
npm notice 1.3kB build/raygun.batch.d.ts
npm notice 5.6kB build/raygun.batch.js
npm notice 1.1kB build/raygun.breadcrumbs.d.ts
npm notice 231B build/raygun.breadcrumbs.express.d.ts
npm notice 930B build/raygun.breadcrumbs.express.js
npm notice 4.7kB build/raygun.breadcrumbs.js
npm notice 5.8kB build/raygun.d.ts
npm notice 645B build/raygun.human.d.ts
npm …
```
=> chore: Prepare release 2.0.0

examples/express-sample/package-lock.json, examples/express-sample/package.json, package-lock.json, package.json
Upgraded express from 4.19.2 to 4.21.2
- **Purpose**: Dependabot sec report
- **Approach**: updates transitive dependency with the issue
**Updates**
:point_right: package.json only
=> chore: Updated package.json to deal with vuln in express dependency

CHANGELOG.md, package-lock.json, package.json
- **Purpose**: Prepare for release
- **Approach**: Bump minor version (because new feature), update CHANGELOG and run `npm audit fix`
**Updates**
- See CHANGELOG
`npm publish --dry-run`
<details>
<summary>Dry run output</summary>
```
➜  raygun4node git:(release-2.2.0) npm publish --dry-run
> raygun@2.2.0 prepare
> tsc
npm notice
npm notice 📦  raygun@2.2.0
npm notice Tarball Contents
npm notice 10.7kB CHANGELOG.md
npm notice 22.7kB README.md
npm notice 0B build/.gitkeep
npm notice 1.3kB build/raygun.batch.d.ts
npm notice 5.6kB build/raygun.batch.js
npm notice 1.1kB build/raygun.breadcrumbs.d.ts
npm notice 231B build/raygun.breadcrumbs.express.d.ts
npm notice 960B build/raygun.breadcrumbs.express.js
npm notice 4.7kB build/raygun.breadcrumbs.js
npm notice 5.8kB …
```
=> chore: Prepare release 2.1.1
