.travis.yml, README.md, lib/raygun.transport.js, package.json
=> May issues

CHANGELOG.md, README.md, lib/raygun.js, lib/raygun.messageBuilder.js, package.json
* adds an option to include column numbers
* if the option is present and true retrieve the column number and include it in the report
* added documentation for the setting
* increment the version
=> Report Column Numbers

package.json
Just click the button to save me a few bytes :)
=> move nock to dev deps

CHANGELOG.md, package.json
Release I forgot to push up the commit for the last release, just bumps the version and updates the changelog.
=> Previous release commit - v0.12.3

CHANGELOG.md, package-lock.json, package.json
Just the version bump and release notes for v0.13.0 😃
=> Release: v0.13.0

package-lock.json, package.json
Just incrementing the version number before release 🙂
=> Release v0.13.2

README.md
This PR is to update the README
Changes made 
- Added section to help users find their API key
- Renamed every where the API key was used to `YOUR_API_KEY` for consistency
- Added section about sourcemaps (copied form public docs)
=> Update Node.js README

.github/dependabot.yml
Adds template for Dependabot config, we can change it in the future.
=> ci: add Dependabot config file

eslint.config.mjs, test/raygun_express_test.js
- **Purpose**: Remove the `no-unreachable` ignore rule on eslint
- **Approach**: Remove the rule and fix code warnings
**Updates**
- Remove the rule from the `eslint.config.mjs`.
- Remove the unreachable code:
- This only affected test files.
- Run the `npm run eslint` and test commands.
=> refactor: #158 configure `no-unreachable` eslint rule

examples/using-domains/package-lock.json
- **Purpose**: Updates the `package-lock.json` after running `npm install`
- **Approach**: Commit changes
This is not an issue, just good to avoid having unrelated changes on other PRs.
**Updates**
- run `npm install` and commited changes
Found out while testing the example that the code changes were not commited to develop.
=> chore: Update package-lock.json in example using-domains

package.json
- **Purpose**: Change author name in package.json
- **Approach**: Update file
Reference: https://github.com/MindscapeHQ/raygun4node/pull/182#discussion_r1588535318
**Updates**
- None
=> chore: change author name

CHANGELOG.md, package-lock.json, package.json
- **Purpose**: Prepare for version `0.15.0-0`
- **Approach**: bump version in package.json and update changelog
**Updates**
- Updated `package.json`
- Updated `changelog.md`
- Performed `npm install`
- None
=> chore: prepare pre-release 0.15.0-0

README.md
- **Purpose**: Replace old greyed out status badge with one from GitHub
- **Approach**: Update README url
**Updates**
- formatted url according to https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge
- click on it opens the https://github.com/MindscapeHQ/raygun4node/actions panel
- Does not apply
=> docs: Update status badge in README.md

CHANGELOG.md, package-lock.json, package.json
- **Purpose**: Prepare for release 1.0.0
- **Approach**: Bump version and update changelog
**Updates**
- Run `npm version major --no-git-tag-version`
- Update changelog
- None
=> chore: Prepare Release 1.0.0

README.md
- **Purpose**: Changes requested in review https://github.com/MindscapeHQ/raygun4node/pull/233
**Updates**
- Updated docs
- None
=> fix: Fixes in 1.0.0 release candidate

lib/raygun.breadcrumbs.ts
- **Purpose**: Adds the `runWithBreadcrumbsAsync` in a separated PR to #244 
- **Approach**: Add function picking changes in file
**Updates**
The changes in the PR #244 require changes in the main project.
Because the new `@raygun/aws-lambda` package would reference the original `raygun` package, a new release with those changes would be necessary.
So we need to approve, merge and release this PR before we can finish the PR #244.
Tested as part of #244
=> feat: Part of #220 add internal runWithBreadcrumbsAsync function

examples/express-sample/views/index.ejs, test/raygun_uncaught_exception_app.js, test/raygun_uncaught_exception_test.js, test/raygun_unhandled_rejection_test.js
- **Purpose**: Addresses comments on release candidate PR https://github.com/MindscapeHQ/raygun4node/pull/252
**Updates**
- Apply suggestion in https://github.com/MindscapeHQ/raygun4node/pull/252#discussion_r1635013628
- Adds comments as requested in https://github.com/MindscapeHQ/raygun4node/pull/252#discussion_r1636049677
- None
=> fix: Fixes on release candidate 1.1.0

README.md, test/raygun.messageBuilder_test.js
- **Purpose**: Provides fixes to review comments in https://github.com/MindscapeHQ/raygun4node/pull/271
**Updates**
- Fix docs.
- Replace string
- None
=> fix: Fixes on 1.2.0 release candidate

eslint.config.mjs, lib/raygun.batch.ts, lib/raygun.breadcrumbs.express.ts, lib/raygun.breadcrumbs.ts, lib/raygun.human.ts, lib/raygun.messageBuilder.ts, lib/raygun.sync.transport.ts, lib/raygun.transport.ts, lib/raygun.ts, package-lock.json, package.json
- **Purpose**: Document methods both internal and public
- Setup tsdoc plugin to help maintain a clean format
- Fix existing documentation
- Add missing documentation
- Closes #161
**Updates**
- Installs and configures the tsdoc eslint plugin.
- Run with `npm run eslint`
- Fix all warnings with existing docs.
- Complete the docs on `raygun.ts` and some of the internal modules.
- No code changes
- eslint should give no warnings if all docs are correctly formatted
=> docs: #161 Document methods using tsdoc format

.github/workflows/node.js.yml
- **Purpose**: Support Node v22 (LTS) as it was released earlier this year.
- **Approach**: Enabled in CI and fix any build issues. Drop v16 from CI as it is no longer maintained.
Reference: https://nodejs.org/en/about/previous-releases
**Updates**
- Updated CI config
- Run eslint, tseslint, tests and prettier locally and on CI
=> feat: Support Node v22

.github/dependabot.yml, .github/workflows/node.js.yml, CHANGELOG.md, README.md, eslint.config.mjs, examples/express-sample/package-lock.json, examples/express-sample/package.json, examples/express-sample/routes/index.js, lib/raygun.breadcrumbs.express.ts, lib/raygun.transport.ts, lib/raygun.ts, lib/types.ts, package-lock.json, package.json, test/raygun_async_send_test.js, tseslint.config.mjs
DO NOT SQUASH, ONLY MERGE
- **Purpose**: Release 2.1.0
- **Approach**: Merge to master
**Updates**
- See CHANGELOG
- None
=> chore: Release 2.1.0

CHANGELOG.md, README.md, examples/express-sample/package-lock.json, examples/express-sample/package.json, package-lock.json, package.json
- **Purpose**: Merge develop into master after release 2.1.1 is published
- **Approach**: MERGE, DO NOT SQUASH
=> chore: Merge develop into master
